Profile epic 3/3
flukekoh/iOS-FakeNFT-StarterProject-Public pull request #14
Opened 2023-10-23 18:24 UTC by flukekoh

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
>          label.textColor = .black
В файле Color  есть static let ypBlack = UIColor(named: "ypBlack")
Надо переписать на: label.textColor = .ypBlack  так как не будет проблем с темной темой

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
>          label.textColor = .black
Тоже самое с цветом  .ypBlack )

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +        noNFTLabel.font = UIFont.systemFont(ofSize: 17, weight: .bold)
static var bodyBold = UIFont.systemFont(ofSize: 17, weight: .bold)

noNFTLabel.font = .bodyBold

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +        noNFTLabel.textColor = .black
static let textPrimary = UIColor.black

noNFTLabel.textColor = .textPrimary

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
>          navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
UIBarButtonItem(
         title: "", 
         style: .plain,
         target: nil,
         action: nil
      )

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
UIAlertController( 
title: title,
 message: message,
 preferredStyle: .alert
) 

Поправь дальше по коду)

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +        return 7
Магические числа)

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +                    //                    }
Не понятный комментарий, наверно надо удалить

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/MyNFT/MyNFTViewModel.swift
> +                    //                    }
Пустой комментарий

2023-10-23 20:44 UTC, RespectRus commented on FakeNFT/Scenes /Profile/ProfileViewModel.swift
> +    func putProfile(name: String?, avatar: String?, description: String?, website: String?, likes: [String]?) {
длинная строка, снеси параметры в столбец

2023-10-23 20:58 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
>          label.textColor = .black
+

2023-10-23 20:58 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
>          label.textColor = .black
+

2023-10-23 20:58 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +        noNFTLabel.font = UIFont.systemFont(ofSize: 17, weight: .bold)
+

2023-10-23 20:58 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +        noNFTLabel.textColor = .black
+

2023-10-23 20:58 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
>          navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
+

2023-10-23 20:58 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
+

2023-10-23 20:58 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +        return 7
+

2023-10-23 20:58 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +                    //                    }
+

2023-10-23 20:59 UTC, flukekoh commented on FakeNFT/Scenes /Profile/MyNFT/MyNFTViewModel.swift
> +                    //                    }
+

2023-10-23 20:59 UTC, flukekoh commented on FakeNFT/Scenes /Profile/ProfileViewModel.swift
> +    func putProfile(name: String?, avatar: String?, description: String?, website: String?, likes: [String]?) {
+

2023-10-26 06:16 UTC, protos17 requested changes

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +//        }
Тут рекомендую добавить:

        didSet {
            onCollectionDataLoad?(collectionData)
        }

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +        onCollectionDataLoad?(loadedData)
Здесь рекомендую заменить на:

collectionData = loadedData

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +            onCollectionDataLoad?(collectionData)
Тут немного ты не допилил функционал, рекомендую добавить:

onCollectionDataLoad?(collectionData.filter { likesIds.contains($0.id) })

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +    let nftNetworkSevice: NFTNetworkSevice?
Рекомендую указать как private

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +    private var nftsIds: [String]
Приватные переменные принято писать после публичных

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Models/Network/NFTNetworkSevice.swift
> +    private var networkClient: NetworkClient = DefaultNetworkClient()
Рекомендую заменить на let - не изменяется

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Models/Network/NFTNetworkSevice.swift
> +                DispatchQueue.global(qos: .background).asyncAfter(deadline: .now() + 3) { // без задержки все время получаю ошибку 429
Обрати внимание, что здесь только switch выполняется в background потоке, а networkClient.send нет

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Models/Network/NFTNetworkSevice.swift
> +                DispatchQueue.global(qos: .background).async {
Здесь тоже только switch в background потоке, а networkClient.send нет

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +    let numberFormatter = NumberFormatter()
Рекомендую указать как private

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +        numberFormatter.numberStyle = .decimal
Для работы с ценами лучше использовать currency:

numberFormatter.numberStyle = .currency

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +
Лучше указать валюту сразу, а потом присваивать только значения:

numberFormatter.currencySymbol = "ETH"

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +            priceLabel.text = "\(formattedString) ETH"
Здесь тогда будет просто:

priceLabel.text = formattedString

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +
Лишний отступ рекомендую убрать

2023-10-26 06:16 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
>      func goBack() {
Рекомендую указать как final

2023-10-26 06:48 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +    let nftNetworkSevice: NFTNetworkSevice?
+

2023-10-26 06:54 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +    private var nftsIds: [String]
+

2023-10-26 06:54 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +    let numberFormatter = NumberFormatter()
+

2023-10-26 06:56 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +
+

2023-10-26 06:57 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +            priceLabel.text = "\(formattedString) ETH"
+

2023-10-26 07:03 UTC, flukekoh commented on FakeNFT/Models/Network/NFTNetworkSevice.swift
> +    private var networkClient: NetworkClient = DefaultNetworkClient()
+

2023-10-26 07:07 UTC, flukekoh commented on FakeNFT/Models/Network/NFTNetworkSevice.swift
> +                DispatchQueue.global(qos: .background).asyncAfter(deadline: .now() + 3) { // без задержки все время получаю ошибку 429
+

2023-10-26 07:07 UTC, flukekoh commented on FakeNFT/Models/Network/NFTNetworkSevice.swift
> +                DispatchQueue.global(qos: .background).async {
+

2023-10-26 07:07 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +        numberFormatter.numberStyle = .decimal
+

2023-10-26 07:07 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTCell.swift
> +
+

2023-10-26 07:07 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
>      func goBack() {
+

2023-10-26 07:37 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +            onCollectionDataLoad?(collectionData)
+

2023-10-26 07:40 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +//        }
Сделал чуть по другому тк в didset у меня получались лишние вызовы апи при например сортировке

2023-10-26 07:40 UTC, flukekoh commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewModel.swift
> +        onCollectionDataLoad?(loadedData)
+

2023-10-27 07:11 UTC, protos17 approved these changes

2023-10-27 07:11 UTC, protos17 commented on FakeNFT/Models/Network/NFTNetworkSevice.swift
> +            DispatchQueue.global(qos: .background).asyncAfter(deadline: .now() + 3) {
В данном случае  [weak self] надо переносить в самое верхнее замыкание при вложенности замыканий

2023-10-27 07:11 UTC, protos17 commented on FakeNFT/Models/Network/NFTNetworkSevice.swift
> +            DispatchQueue.global(qos: .background).async {
Этот [weak self] тоже необходимо перенести на уровень выше на эту строку

2023-10-27 07:11 UTC, protos17 commented on FakeNFT/Scenes /Profile/FavoriteNFT/FavoriteNFTViewController.swift
> +    final private func goBack() {
final используется чтобы показать, что метод не будет переопределен при наследовании, тут никакого наследования не предполагается, поэтому final нужно убрать

2023-10-27 07:11 UTC, protos17 commented on FakeNFT/Scenes /Profile/ProfileViewModel.swift
> +            self.networkClient.send(request: request, type: ProfileNetworkModel.self) { [self] result in
Необходимо захватывать self слабым - weak или unowned, в текущем варианте его нужно перенести на строчку выше и указать слабым, иначе это сильная ссылка

2023-10-27 07:11 UTC, protos17 commented on FakeNFT/Scenes /Profile/ProfileViewModel.swift
> +            self.networkClient.send(request: request, type: ProfileNetworkModel.self) { [self] result in
Здесь то же самое, необходимо перенести на уровень замыкания выше на 61 строчку и указать как weak

2023-10-27 08:27 UTC, merged